spring:
  application:
    name: chat-gpt-telegram-bot

server:
  port: 8080

bot:
  key: zero
  name: zero
  owner-chatId: zero

openai:
  api:
    key: key
    chat-url: urla
    chat-model: modla
    chat-system-role: rolla
    transcription-url: transa
    voice-model: modla
    language: langa
